services:
  - type: web
    name: fraudshield-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r fraud-detection-system/backend/requirements.txt && cd fraud-detection-system/backend/models && python3 train_model.py
    startCommand: cd fraud-detection-system/backend && python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false

databases:
  - name: fraudshield-db
    plan: free
    region: oregon
